### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by kun-shukla**

### CODE REVIEW

**Review by simonpartridge86 — APPROVED** [review]
Lovely stuff Kunal and Sam

**Review by AdamPhasey — COMMENTED** [review]
Needs fixing with regards to the conflicts

**Review by samsonhumber — APPROVED** [review]
I saw it earlier so I am happy to approve the merge

**Review by mauriziomonti — APPROVED** [review]

**Review by minodevito — APPROVED** [review]
Good job!

**Review by AdamPhasey — APPROVED** [review]

**Pull request merged**
